name: JSON checks

on:
  push:
    paths:
      - '**.json'
  pull_request:

jobs:
  syntax:
    name: Validate JSON syntax
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: json-syntax-check
        # Awaiting merge of limitusus/json-syntax-check#8
        uses: dgw/json-syntax-check@b932368c8b77ff63b22ba5165ae3aa96aa6a9051
        env:
          BASE: /github/workspace
        with:
          pattern: "\\.json$"
  schema:
    name: Validate JSON schema
    runs-on: ubuntu-20.04
    needs: syntax
    steps:
      - uses: actions/checkout@v2
      - name: install-jsonschema
        run: pip3 install jsonschema
      - name: json-schema-check
        run: jsonschema --instance sopel_waifu/waifu.json sopel_waifu/waifu.json.schema
